"""timecapsule daemon — entry point that wires watcher, git, store, and narrator.

Watches a directory tree for file changes. After 2 minutes of inactivity
on a file, snapshots it to the timecapsule repo with a narrative commit
message (generated by Ollama if available, otherwise structural)."""

import argparse
import os
import signal
import sys
import time
from pathlib import Path

from . import git_ops
from .store import TimelineStore
from .watcher import FileWatcher, IDLE_SECONDS


def _snapshot_callback(filepath: str):
    """Called when a file has been idle long enough to snapshot."""
    from .narrator import generate_message as gen_msg

    store = TimelineStore()
    repo = git_ops.ensure_repo()

    # Get current content
    if not os.path.isfile(filepath):
        return

    with open(filepath, "rb") as f:
        current_content = f.read().decode("utf-8", errors="replace")

    # Get previous snapshot content and message for context
    branch = git_ops._branch_name(filepath)
    previous_content = None
    previous_message = None

    try:
        commits = list(repo.iter_commits(branch, max_count=1))
        if commits:
            previous_message = commits[0].message.strip()
            rel_path = os.path.basename(filepath)
            try:
                previous_content = repo.git.show(f"{commits[0].hexsha}:{rel_path}")
            except Exception:
                previous_content = None
    except Exception:
        pass

    # Generate narrative message
    message = gen_msg(
        filepath=filepath,
        current_content=current_content,
        previous_content=previous_content,
        previous_message=previous_message,
    )

    # Snapshot to git
    hexsha = git_ops.snapshot_file(filepath, message, repo)
    if hexsha:
        store.record_snapshot(filepath, hexsha, message, branch)
        print(f"[snapshot] {os.path.basename(filepath)} › {message[:60]}...", flush=True)


def _rename_callback(old_path: str, new_path: str):
    """Called when a file is renamed/moved.
    Continues the snapshot history on the same branch.
    """
    from .narrator import generate_message as gen_msg

    store = TimelineStore()
    repo = git_ops.ensure_repo()

    old_name = os.path.basename(old_path)
    new_name = os.path.basename(new_path)
    message = f"Renamed {old_name} to {new_name}"

    if os.path.isfile(new_path):
        with open(new_path, "rb") as f:
            current_content = f.read().decode("utf-8", errors="replace")

        # Try to get previous message from the OLD branch
        old_branch = git_ops._branch_name(old_path)
        previous_message = None
        try:
            commits = list(repo.iter_commits(old_branch, max_count=1))
            if commits:
                previous_message = commits[0].message.strip()
        except Exception:
            pass

        narrative = gen_msg(
            filepath=new_path,
            current_content=current_content,
            previous_content=None,
            previous_message=previous_message,
        )
        message = f"{message} — {narrative}"

        branch = git_ops._branch_name(new_path)
        hexsha = git_ops.snapshot_file(new_path, message, repo)
        if hexsha:
            store.record_snapshot(new_path, hexsha, message, branch)
            print(f"[rename] {old_name} → {new_name}", flush=True)
    """Start the file watcher and run until interrupted."""
    print(f"🕰️  timecapsule watching: {', '.join(paths)}")
    print(f"   idle threshold: {idle}s | snapshots: ~/.capsule/timecapsule")
    print(f"   press Ctrl+C to stop\n")

    watcher = FileWatcher(paths, _snapshot_callback, rename_callback=_rename_callback, idle_seconds=idle)

    def _handle_signal(sig, frame):
        watcher.stop()
        sys.exit(0)

    signal.signal(signal.SIGINT, _handle_signal)
    signal.signal(signal.SIGTERM, _handle_signal)

    watcher.start()
    print("   ✓ watcher started")

    # If --once, do one pass of all files and exit
    if once:
        _scan_all_files(paths)
        watcher.stop()
        print("\n   ✓ one-time scan complete")
        return

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        pass
    finally:
        watcher.stop()
        print("\n   ✗ watcher stopped")


def _scan_all_files(paths: list[str]):
    """Immediately snapshot all tracked files (one-time mode)."""
    from .narrator import generate_message as gen_msg

    store = TimelineStore()
    repo = git_ops.ensure_repo()

    ext_filter = {
        ".py", ".js", ".ts", ".rs", ".go", ".md",
        ".txt", ".json", ".yaml", ".toml", ".css",
        ".html", ".jsx", ".tsx", ".java", ".c", ".cpp",
        ".h", ".sh", ".ps1", ".bat", ".sql", ".rb",
        ".php", ".swift", ".kt", ".scala", ".zig",
    }

    for root_path in paths:
        for dirpath, _, filenames in os.walk(root_path):
            for fn in filenames:
                if fn.startswith(".") or fn.startswith("__"):
                    continue
                ext = os.path.splitext(fn)[1].lower()
                if ext in ext_filter:
                    fp = os.path.join(dirpath, fn)
                    _snapshot_callback(fp)


def main():
    parser = argparse.ArgumentParser(
        description="🕰️  timecapsule — narrative snapshots of your work",
    )
    parser.add_argument(
        "paths", nargs="*", default=["."],
        help="Directories to watch (default: current directory)",
    )
    parser.add_argument(
        "--idle", type=int, default=IDLE_SECONDS,
        help=f"Idle seconds before snapshot (default: {IDLE_SECONDS})",
    )
    parser.add_argument(
        "--once", action="store_true",
        help="Snapshot all files once and exit (no daemon)",
    )
    parser.add_argument(
        "--browse", action="store_true",
        help="Open the timeline browser TUI",
    )
    parser.add_argument(
        "--status", action="store_true",
        help="Show capsule stats and exit",
    )

    args = parser.parse_args()

    if args.browse:
        from .tui import run_browser
        run_browser()
        return

    if args.status:
        store = TimelineStore()
        repo = git_ops.ensure_repo()
        count = store.total_snapshots()
        files = len(store.get_all_files())
        repo_path = str(git_ops.REPO_PATH)
        print(f"🕰️  timecapsule status")
        print(f"   snapshots: {count}")
        print(f"   tracked files: {files}")
        print(f"   repository: {repo_path}")
        return

    watch(args.paths, idle=args.idle, once=args.once)


if __name__ == "__main__":
    main()
